name: pigeon-pack
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - folium
  - huggingface_hub
  - ipywidgets
  - jinja2
  - jupyter
  - markupsafe
  - matplotlib-base
  - matplotlib-inline
  - nbconvert
  - nbformat
  - notebook
  - numpy
  - pandas
  - pip
  - pynvml
  - pytorch
  - scikit-learn
  - scipy
  - tqdm
  - georasters
  - pandarallel
  - pygeos
  - datasets
  - shapely=1.8.5
  - geopandas
  - pycountry
  - transformers
  - pip:
    - latlon_utils
    - datasets
    - global_land_mask
    - srtm-py
    - condacolab
    - accelerate