channels:
  - conda-forge
  - pytorch
  - huggingface
  - defaults
dependencies:
  - fiona=1.8.21
  - folium=0.13.0
  - geopandas=0.11.1
  - huggingface_hub=0.10.1
  - ipython=8.3.0
  - ipywidgets=7.6.5
  - jinja2=3.0.3
  - jupyter=1.0.0
  - markupsafe=2.1.1
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.2
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - notebook=6.4.11
  - numpy=1.26.4
  - pandas=1.4.2
  - pip=22.2.2
  - pynvml=11.4.1 
  - python=3.8.10
  - pytorch=1.12.0
  - scikit-learn=1.1.1
  - scipy=1.6.2
  - torchvision=0.10.0
  - tornado=6.1
  - tqdm=4.67.1
  - pip:
    - accelerate==0.26.0
    - captum==0.5.0
    - datasets==2.6.1
    - fastapi==0.88.0
    - ftfy==6.1.1
    - georasters==0.5.23
    - geopy==2.3.0
    - latlon-utils==0.0.7
    - pandarallel==1.6.3
    - python-datauri==1.1.0
    - reverse-geocoder==1.5.1
    - shapely==1.8.5.post1
    - srtm-py==0.3.7
    - tokenizers==0.20.0
    - torch-summary==1.4.5
    - torch-tb-profiler==0.4.0
    - transformers==4.46.0
    - uvicorn==0.19.0